#170947384 Implement requests table
atlp-rwanda/octopus-bn-frontend pull request #13
Opened 2020-05-09 10:51 UTC by blaise82

## **Why**
The requests table is handy in displaying a users requests.

A logged in user should see the travel requests table along with the details of the requests that they have made.

## **Acceptance Criteria**
**Scenario:** 
```
When a user is on the requests page they should see the requests table.```

Sync with other colleagues implementing other aspects of the page to agree on the details to be seen on the table

#### Description of Task to be completed? 
- set up requests redux state
- create table 
- handle pagination
- fetch requests from the database

#### How should this be manually tested?
- open your terminal
- clone this repo by `git clone https://github.com/Stackup-Rwanda/octopus-bn-frontend`
- run `cd octopus-bn-frontend` to move to the project folder
- run `git checkout ` to move to this branch 
- run `npm install` to install all required dependencies for this feature
- run 'npm run dev' to start the development server 

> will open the project on an 8080 port so to access the project you will need to open your browser and load `http://localhost:8080` {port}

- you will presented with the login page use the credentials below to log in
```
email: octopusbn@gmail.com
password: password
```
- load `http://localhost:8080/requests` or click on `My REQUESTS` option on the drawer to load  `http://localhost:8080/requests

#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2020-05-09 at 12 50 36" src="https://user-images.githubusercontent.com/52036624/81471760-b9e38e80-91f3-11ea-852c-b3d79c82e038.png">

[starts #170947384]

2020-05-12 10:04 UTC, hakoemmy reviewed
@blaise82 You did an interesting job, Would you please raise your tests coverage.

2020-05-13 10:55 UTC, hakoemmy reviewed
@blaise82 Address the minor comments left

2020-05-13 10:55 UTC, hakoemmy commented on src/redux/reducers/requestsReducer.js
> +		// 	};
```suggestion
	
```
Get a rid of the comments if you they don't add any value

2020-05-13 10:55 UTC, hakoemmy commented on src/styles/dashboard.requests.module.css
> +}
```suggestion
}

```
EOF

2020-05-13 11:15 UTC, hakoemmy approved these changes
@blaise82 You did a great job. Keep it up

2020-05-13 11:21 UTC, Moise1 requested changes
@blaise82 , please provide a proper message when a logged in user is trying to view their requests yet they have none.

2020-05-13 12:28 UTC, Moise1 approved these changes

2020-05-13 20:28 UTC, AbdoulNuru approved these changes

2020-05-14 14:13 UTC, AJAkimana reviewed
As the whole app is using arrow functions, do the same in this PR in order to keep code consistency

2020-05-14 14:13 UTC, AJAkimana commented on src/components/RequestsTable.js
> +function TablePaginationActions(props) {
Use arrow function

2020-05-14 14:13 UTC, AJAkimana commented on src/components/RequestsTable.js
> +export default function RequestsTable() {
Use an arrow function

2020-05-14 14:13 UTC, AJAkimana commented on src/components/ResponsiveDrawer.js
>  function ResponsiveDrawer(props) {
Use arrow function

2020-05-15 08:10 UTC, merged