#172888737 Create rooms
atlp-rwanda/octopus-bn-frontend pull request #22
Opened 2020-05-19 23:02 UTC by AbdoulNuru

#### What does this PR do?
- implement create rooms in accommodation centres functionality
#### Description of Task to be completed?
- create a component to be used creating rooms
- test the functionality
#### How should this be manually tested?
- clone the repo, then checkout to this branch ``ft-create-rooms-172888737``
- run `npm i` to install all project dependencies
- run `npm run dev` to start the development server
- login as a travel administrator and on your dashboard go to add rooms to create a room in an accommodation facility, use credentials below to login
```
email: octopusbn@gmail.com
password: password
```
#### What are the relevant pivotal tracker stories?
[#172888737](https://www.pivotaltracker.com/story/show/172888737)
#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2020-05-20 at 00 16 13" src="https://user-images.githubusercontent.com/53453380/82386757-7e3b9680-9a35-11ea-9568-ec851d819477.png">

2020-05-21 11:12 UTC, blaise82 approved these changes

2020-05-21 12:42 UTC, hakoemmy approved these changes
@AbdoulNuru Well done

2020-05-21 13:31 UTC, Moise1 approved these changes
Good job!

2020-05-22 08:40 UTC, AJAkimana requested changes
Name variables according to their function. So that in the future you will know what the variable, the function does without double-checking

2020-05-22 08:40 UTC, AJAkimana commented on src/styles/signup.module.css
> +.forms_plus2 {
Use descriptive variable name

2020-05-22 08:40 UTC, AJAkimana commented on src/styles/signup.module.css
> +.wrap3 {
Descriptive variable name

2020-05-22 08:40 UTC, AJAkimana commented on src/styles/signup.module.css
> +.wrap1 {
Use descriptive variable name

2020-05-22 08:40 UTC, AJAkimana commented on src/styles/signup.module.css
> +  .forms_plus2 {
Use descriptive variable name

2020-05-22 08:40 UTC, AJAkimana commented on src/views/Dashboard/CreateRooms.js
> +import styles2 from "../../styles/addAccom.module.css";
Use descriptive variable name

2020-05-26 13:01 UTC, AJAkimana approved these changes

2020-05-26 13:01 UTC, merged