#170947395 Users should be able to search
atlp-rwanda/octopus-bn-frontend pull request #25
Opened 2020-06-01 12:44 UTC by blaise82

Search Function

## **Why**
As requests and approval tables grow, it should be easy to find requests through the search functionality

**As a user,** I should be able to use the search component
So, I can easily retrieve records from both the request and approval table

## **Acceptance Criteria**
- Given that a user is logged in, when the user enters data into the search component, then the records displayed in the table should reflect all possible records relevant to the content of the  data entered by the user in the search component
- User should be able to search based on the column headers which are: request ID, owner, destination, origin, duration, start date, request status etc

#### Description of Task to be completed?
- search through array

#### How should this be manually tested?

- open your terminal
- clone this repo by `git clone https://github.com/Stackup-Rwanda/octopus-bn-frontend`
- run `cd octopus-bn-frontend` to move to the project folder
- run `git checkout  ft-avail-requests-#170947390` to move to this branch 
- run `npm install` to install all required dependencies for this feature
- run 'npm run dev' to start the development server 

#### Screenshots (if appropriate)
Before 

![image](https://user-images.githubusercontent.com/52036624/83410248-53c6e180-a416-11ea-8c86-1bb0ce07cc01.png)

After
![image](https://user-images.githubusercontent.com/52036624/83410187-2c701480-a416-11ea-909c-a1ae3c2997da.png)

https://www.pivotaltracker.com/story/show/170947395

[finishes #170947395]

2020-06-02 08:26 UTC, hakoemmy reviewed
@blaise82 Good job for implementing this cool search functionality, however, can you fix coverage decrease issues?

2020-06-03 19:24 UTC, AbdoulNuru submitted a review, later dismissed

2020-06-04 09:40 UTC, hakoemmy approved these changes

2020-06-04 10:09 UTC, Moise1 commented
@blaise82 , would you please highlight the search area to make it more visible?

2020-06-04 10:12 UTC, Moise1 requested changes
Blaise, may you please highlight the search area to make it more visible to the user?

2020-06-04 10:21 UTC, AbdoulNuru approved these changes

2020-06-04 10:44 UTC, Moise1 approved these changes

2020-06-04 13:24 UTC, merged